services:
  # Frontend Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - incuca-network

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://incuca:secret@database:5432/incuca
      - JWT_SECRET=your-super-secret-jwt-key-here-should-be-very-long-and-random
      - JWT_EXPIRES_IN=7d
      - GEEK_JOKES_API_URL=https://geek-jokes.sameerkumar.website/api
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - database
    networks:
      - incuca-network

  # PostgreSQL Database
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=incuca
      - POSTGRES_USER=incuca
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - incuca-network


volumes:
  postgres_data:

networks:
  incuca-network:
    driver: bridge
